/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CreatorRouteImport } from "./routes/_creator";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as CreatorDashboardRouteImport } from "./routes/_creator/dashboard";
import { Route as CreatorRoomsRoomIdRouteImport } from "./routes/_creator/rooms.$roomId";
import { Route as CreatorRoomsNewRouteImport } from "./routes/_creator/rooms.new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorRoute = CreatorRouteImport.update({
  id: "/_creator",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => CreatorRoute,
} as any);
const CreatorRoomsRoomIdRoute = CreatorRoomsRoomIdRouteImport.update({
  id: "/rooms/$roomId",
  path: "/rooms/$roomId",
  getParentRoute: () => CreatorRoute,
} as any);
const CreatorRoomsNewRoute = CreatorRoomsNewRouteImport.update({
  id: "/rooms/new",
  path: "/rooms/new",
  getParentRoute: () => CreatorRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/dashboard": typeof CreatorDashboardRoute;
  "/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/rooms/new": typeof CreatorRoomsNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-in": typeof SignInRoute;
  "/dashboard": typeof CreatorDashboardRoute;
  "/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/rooms/new": typeof CreatorRoomsNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_creator": typeof CreatorRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/_creator/dashboard": typeof CreatorDashboardRoute;
  "/_creator/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/_creator/rooms/new": typeof CreatorRoomsNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/sign-in" | "/dashboard" | "/rooms/$roomId" | "/rooms/new";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/sign-in" | "/dashboard" | "/rooms/$roomId" | "/rooms/new";
  id:
    | "__root__"
    | "/"
    | "/_creator"
    | "/sign-in"
    | "/_creator/dashboard"
    | "/_creator/rooms/$roomId"
    | "/_creator/rooms/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreatorRoute: typeof CreatorRouteWithChildren;
  SignInRoute: typeof SignInRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator": {
      id: "/_creator";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof CreatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator/dashboard": {
      id: "/_creator/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof CreatorDashboardRouteImport;
      parentRoute: typeof CreatorRoute;
    };
    "/_creator/rooms/$roomId": {
      id: "/_creator/rooms/$roomId";
      path: "/rooms/$roomId";
      fullPath: "/rooms/$roomId";
      preLoaderRoute: typeof CreatorRoomsRoomIdRouteImport;
      parentRoute: typeof CreatorRoute;
    };
    "/_creator/rooms/new": {
      id: "/_creator/rooms/new";
      path: "/rooms/new";
      fullPath: "/rooms/new";
      preLoaderRoute: typeof CreatorRoomsNewRouteImport;
      parentRoute: typeof CreatorRoute;
    };
  }
}

interface CreatorRouteChildren {
  CreatorDashboardRoute: typeof CreatorDashboardRoute;
  CreatorRoomsRoomIdRoute: typeof CreatorRoomsRoomIdRoute;
  CreatorRoomsNewRoute: typeof CreatorRoomsNewRoute;
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorRoomsRoomIdRoute: CreatorRoomsRoomIdRoute,
  CreatorRoomsNewRoute: CreatorRoomsNewRoute,
};

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
  SignInRoute: SignInRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
