/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CreatorRouteImport } from "./routes/_creator";
import { Route as CreatorDashboardRouteImport } from "./routes/_creator/dashboard";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorRoute = CreatorRouteImport.update({
  id: "/_creator",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => CreatorRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof CreatorDashboardRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof CreatorDashboardRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_creator": typeof CreatorRouteWithChildren;
  "/_creator/dashboard": typeof CreatorDashboardRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard";
  id: "__root__" | "/" | "/_creator" | "/_creator/dashboard";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreatorRoute: typeof CreatorRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator": {
      id: "/_creator";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof CreatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator/dashboard": {
      id: "/_creator/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof CreatorDashboardRouteImport;
      parentRoute: typeof CreatorRoute;
    };
  }
}

interface CreatorRouteChildren {
  CreatorDashboardRoute: typeof CreatorDashboardRoute;
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorDashboardRoute: CreatorDashboardRoute,
};

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
