/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CreatorRouteImport } from "./routes/_creator";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as CreatorDashboardRouteImport } from "./routes/_creator/dashboard";
import { Route as RShareTokenRouteImport } from "./routes/r.$shareToken";
import { Route as CreatorRoomsRoomIdRouteImport } from "./routes/_creator/rooms.$roomId";
import { Route as CreatorRoomsNewRouteImport } from "./routes/_creator/rooms.new";
import { Route as RShareTokenResultsRouteImport } from "./routes/r.$shareToken_.results";
import { Route as CreatorRoomsRoomIdResultsRouteImport } from "./routes/_creator/rooms.$roomId_.results";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorRoute = CreatorRouteImport.update({
  id: "/_creator",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => CreatorRoute,
} as any);
const RShareTokenRoute = RShareTokenRouteImport.update({
  id: "/r/$shareToken",
  path: "/r/$shareToken",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorRoomsRoomIdRoute = CreatorRoomsRoomIdRouteImport.update({
  id: "/rooms/$roomId",
  path: "/rooms/$roomId",
  getParentRoute: () => CreatorRoute,
} as any);
const CreatorRoomsNewRoute = CreatorRoomsNewRouteImport.update({
  id: "/rooms/new",
  path: "/rooms/new",
  getParentRoute: () => CreatorRoute,
} as any);
const RShareTokenResultsRoute = RShareTokenResultsRouteImport.update({
  id: "/r/$shareToken_/results",
  path: "/r/$shareToken/results",
  getParentRoute: () => rootRouteImport,
} as any);
const CreatorRoomsRoomIdResultsRoute =
  CreatorRoomsRoomIdResultsRouteImport.update({
    id: "/rooms/$roomId_/results",
    path: "/rooms/$roomId/results",
    getParentRoute: () => CreatorRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/dashboard": typeof CreatorDashboardRoute;
  "/r/$shareToken": typeof RShareTokenRoute;
  "/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/rooms/new": typeof CreatorRoomsNewRoute;
  "/r/$shareToken/results": typeof RShareTokenResultsRoute;
  "/rooms/$roomId/results": typeof CreatorRoomsRoomIdResultsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/dashboard": typeof CreatorDashboardRoute;
  "/r/$shareToken": typeof RShareTokenRoute;
  "/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/rooms/new": typeof CreatorRoomsNewRoute;
  "/r/$shareToken/results": typeof RShareTokenResultsRoute;
  "/rooms/$roomId/results": typeof CreatorRoomsRoomIdResultsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_creator": typeof CreatorRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/_creator/dashboard": typeof CreatorDashboardRoute;
  "/r/$shareToken": typeof RShareTokenRoute;
  "/_creator/rooms/$roomId": typeof CreatorRoomsRoomIdRoute;
  "/_creator/rooms/new": typeof CreatorRoomsNewRoute;
  "/r/$shareToken_/results": typeof RShareTokenResultsRoute;
  "/_creator/rooms/$roomId_/results": typeof CreatorRoomsRoomIdResultsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/forgot-password"
    | "/reset-password"
    | "/sign-in"
    | "/dashboard"
    | "/r/$shareToken"
    | "/rooms/$roomId"
    | "/rooms/new"
    | "/r/$shareToken/results"
    | "/rooms/$roomId/results";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/reset-password"
    | "/sign-in"
    | "/dashboard"
    | "/r/$shareToken"
    | "/rooms/$roomId"
    | "/rooms/new"
    | "/r/$shareToken/results"
    | "/rooms/$roomId/results";
  id:
    | "__root__"
    | "/"
    | "/_creator"
    | "/forgot-password"
    | "/reset-password"
    | "/sign-in"
    | "/_creator/dashboard"
    | "/r/$shareToken"
    | "/_creator/rooms/$roomId"
    | "/_creator/rooms/new"
    | "/r/$shareToken_/results"
    | "/_creator/rooms/$roomId_/results";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreatorRoute: typeof CreatorRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SignInRoute: typeof SignInRoute;
  RShareTokenRoute: typeof RShareTokenRoute;
  RShareTokenResultsRoute: typeof RShareTokenResultsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator": {
      id: "/_creator";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof CreatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator/dashboard": {
      id: "/_creator/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof CreatorDashboardRouteImport;
      parentRoute: typeof CreatorRoute;
    };
    "/r/$shareToken": {
      id: "/r/$shareToken";
      path: "/r/$shareToken";
      fullPath: "/r/$shareToken";
      preLoaderRoute: typeof RShareTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator/rooms/$roomId": {
      id: "/_creator/rooms/$roomId";
      path: "/rooms/$roomId";
      fullPath: "/rooms/$roomId";
      preLoaderRoute: typeof CreatorRoomsRoomIdRouteImport;
      parentRoute: typeof CreatorRoute;
    };
    "/_creator/rooms/new": {
      id: "/_creator/rooms/new";
      path: "/rooms/new";
      fullPath: "/rooms/new";
      preLoaderRoute: typeof CreatorRoomsNewRouteImport;
      parentRoute: typeof CreatorRoute;
    };
    "/r/$shareToken_/results": {
      id: "/r/$shareToken_/results";
      path: "/r/$shareToken/results";
      fullPath: "/r/$shareToken/results";
      preLoaderRoute: typeof RShareTokenResultsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_creator/rooms/$roomId_/results": {
      id: "/_creator/rooms/$roomId_/results";
      path: "/rooms/$roomId/results";
      fullPath: "/rooms/$roomId/results";
      preLoaderRoute: typeof CreatorRoomsRoomIdResultsRouteImport;
      parentRoute: typeof CreatorRoute;
    };
  }
}

interface CreatorRouteChildren {
  CreatorDashboardRoute: typeof CreatorDashboardRoute;
  CreatorRoomsRoomIdRoute: typeof CreatorRoomsRoomIdRoute;
  CreatorRoomsNewRoute: typeof CreatorRoomsNewRoute;
  CreatorRoomsRoomIdResultsRoute: typeof CreatorRoomsRoomIdResultsRoute;
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorRoomsRoomIdRoute: CreatorRoomsRoomIdRoute,
  CreatorRoomsNewRoute: CreatorRoomsNewRoute,
  CreatorRoomsRoomIdResultsRoute: CreatorRoomsRoomIdResultsRoute,
};

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  RShareTokenRoute: RShareTokenRoute,
  RShareTokenResultsRoute: RShareTokenResultsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
